// LOADING
export const COMMENT_LOADING_REQUEST = 'COMMENT_LOADING_REQUEST';
export const COMMENT_LOADING_SUCCESS = 'COMMENT_LOADING_SUCCESS';
export const COMMENT_LOADING_FAILURE = 'COMMENT_LOADING_FAILURE';

// UPLOADING
export const COMMENT_UPLOADING_REQUEST = 'COMMENT_UPLOADING_REQUEST';
export const COMMENT_UPLOADING_SUCCESS = 'COMMENT_UPLOADING_SUCCESS';
export const COMMENT_UPLOADING_FAILURE = 'COMMENT_UPLOADING_FAILURE';

// EDIT
export const COMMENT_EDIT_REQUEST = 'COMMENT_EDIT_REQUEST';
export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
export const COMMENT_EDIT_FAILURE = 'COMMENT_EDIT_FAILURE';

// DELETE
export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';
