// CREATE
export const PROJECT_WRITE_REQUEST = 'PROJECT_WRITE_REQUEST';
export const PROJECT_WRITE_SUCCESS = 'PROJECT_WRITE_SUCCESS';
export const PROJECT_WRITE_FAILURE = 'PROJECT_WRITE_FAILURE';

// READ // DETAIL
export const PROJECT_DETAIL_REQUEST = 'PROJECT_DETAIL_REQUEST';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_DETAIL_FAILURE = 'PROJECT_DETAIL_FAILURE';

// READ // LIST
export const PROJECT_LOADING_REQUEST = 'PROJECT_LOADING_REQUEST';
export const PROJECT_LOADING_SUCCESS = 'PROJECT_LOADING_SUCCESS';
export const PROJECT_LOADING_FAILURE = 'PROJECT_LOADING_FAILURE';

// UPDATE // PAGE
export const PROJECT_EDITPAGE_REQUEST = 'PROJECT_EDITPAGE_REQUEST';
export const PROJECT_EDITPAGE_SUCCESS = 'PROJECT_EDITPAGE_SUCCESS';
export const PROJECT_EDITPAGE_FAILURE = 'PROJECT_EDITPAGE_FAILURE';

// UPDATE // ACTION
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

// DELETE
export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

//COMMENT_DELETE
export const PROJECT_COMMENT_DELETE_REQUEST = 'PROJECT_COMMENT_DELETE_REQUEST';
export const PROJECT_COMMENT_DELETE_SUCCESS = 'PROJECT_COMMENT_DELETE_SUCCESS';
export const PROJECT_COMMENT_DELETE_FAILURE = 'PROJECT_COMMENT_DELETE_FAILURE';

//COMMENT_LOADING
export const PROJECT_COMMENT_LOADING_REQUEST =
  'PROJECT_COMMENT_LOADING_REQUEST';

//COMMENT_UPLOADING
export const PROJECT_COMMENT_UPLOADING_REQUEST =
  'PROJECT_COMMENT_UPLOADING_REQUEST';

// CATEGORY FIND
export const CATEGORY_FIND_REQUEST = 'CATEGORY_FIND_REQUEST';
export const CATEGORY_FIND_SUCCESS = 'CATEGORY_FIND_SUCCESS';
export const CATEGORY_FIND_FAILURE = 'CATEGORY_FIND_FAILURE';
