// CREATE
export const PROJECT_WRITE_REQUEST = 'PROJECT_WRITE_REQUEST';
export const PROJECT_WRITE_SUCCESS = 'PROJECT_WRITE_SUCCESS';
export const PROJECT_WRITE_FAILURE = 'PROJECT_WRITE_FAILURE';

// READ // DETAIL
export const PROJECT_DETAIL_REQUEST = 'PROJECT_DETAIL_REQUEST';
export const PROJECT_DETAIL_SUCCESS = 'PROJECT_DETAIL_SUCCESS';
export const PROJECT_DETAIL_FAILURE = 'PROJECT_DETAIL_FAILURE';

// READ // LIST
export const PROJECT_LOADING_REQUEST = 'PROJECT_LOADING_REQUEST';
export const PROJECT_LOADING_SUCCESS = 'PROJECT_LOADING_SUCCESS';
export const PROJECT_LOADING_FAILURE = 'PROJECT_LOADING_FAILURE';

// UPDATE // PAGE
export const PROJECT_EDITPAGE_REQUEST = 'PROJECT_EDITPAGE_REQUEST';
export const PROJECT_EDITPAGE_SUCCESS = 'PROJECT_EDITPAGE_SUCCESS';
export const PROJECT_EDITPAGE_FAILURE = 'PROJECT_EDITPAGE_FAILURE';

// UPDATE // ACTION
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAILURE = 'PROJECT_UPDATE_FAILURE';

// DELETE
export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAILURE = 'PROJECT_DELETE_FAILURE';

//COMMENT_DELETE
export const COMMENT_DELETE_REQUEST = 'COMMENT_DELETE_REQUEST';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';
export const COMMENT_DELETE_FAILURE = 'COMMENT_DELETE_FAILURE';

//COMMENT_LOADING
export const COMMENT_LOADING_REQUEST = 'COMMENT_LOADING_REQUEST';
export const COMMENT_LOADING_SUCCESS = 'COMMENT_LOADING_SUCCESS';
export const COMMENT_LOADING_FAILURE = 'COMMENT_LOADING_FAILURE';

//COMMENT_UPLOADING
export const COMMENT_UPLOADING_REQUEST = 'COMMENT_UPLOADING_REQUEST';
export const COMMENT_UPLOADING_SUCCESS = 'COMMENT_UPLOADING_SUCCESS';
export const COMMENT_UPLOADING_FAILURE = 'COMMENT_UPLOADING_FAILURE';

//COMMENT_EDIT
export const COMMENT_EDIT_REQUEST = 'COMMENT_EDIT_REQUEST';
export const COMMENT_EDIT_SUCCESS = 'COMMENT_EDIT_SUCCESS';
export const COMMENT_EDIT_FAILURE = 'COMMENT_EDIT_FAILURE';
